### ISSUE TITLE
Built-in activators

### ISSUE THREAD

**Issue by morfeusys** [just-ai/jaicf-kotlin#56]
Let’s think about making CatchAllActivator, BaseEventActivator and RegexActivator built into the framework, enabling the user skip these activators from the list of BotEngine instance.

**Comment by Denire** [comment]
I like this idea. But also:
1. I've never seen when user wanted to exclude these activators. Why make them default without option to skip them?
2. What happens if we need to sort them in custom order? For example, when `BaseEventActivator` should be higher than any of IntentActivators? Skipping won't be an option.
